development:
  forest_env_secret: 11ea897ae8bdd1248281535208b2d15c90ccf437b17640b7723c84ab43e91495
  forest_auth_secret: O_LC62-JS8hxShRo0xPvlg
  forest_application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
